/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WillsProbateRouteImport } from './routes/wills-probate'
import { Route as ImmigrationRouteImport } from './routes/immigration'
import { Route as ConveyancingRouteImport } from './routes/conveyancing'
import { Route as CommercialPropertyRouteImport } from './routes/commercial-property'
import { Route as IndexRouteImport } from './routes/index'

const WillsProbateRoute = WillsProbateRouteImport.update({
  id: '/wills-probate',
  path: '/wills-probate',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmigrationRoute = ImmigrationRouteImport.update({
  id: '/immigration',
  path: '/immigration',
  getParentRoute: () => rootRouteImport,
} as any)
const ConveyancingRoute = ConveyancingRouteImport.update({
  id: '/conveyancing',
  path: '/conveyancing',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialPropertyRoute = CommercialPropertyRouteImport.update({
  id: '/commercial-property',
  path: '/commercial-property',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commercial-property': typeof CommercialPropertyRoute
  '/conveyancing': typeof ConveyancingRoute
  '/immigration': typeof ImmigrationRoute
  '/wills-probate': typeof WillsProbateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commercial-property': typeof CommercialPropertyRoute
  '/conveyancing': typeof ConveyancingRoute
  '/immigration': typeof ImmigrationRoute
  '/wills-probate': typeof WillsProbateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commercial-property': typeof CommercialPropertyRoute
  '/conveyancing': typeof ConveyancingRoute
  '/immigration': typeof ImmigrationRoute
  '/wills-probate': typeof WillsProbateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commercial-property'
    | '/conveyancing'
    | '/immigration'
    | '/wills-probate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commercial-property'
    | '/conveyancing'
    | '/immigration'
    | '/wills-probate'
  id:
    | '__root__'
    | '/'
    | '/commercial-property'
    | '/conveyancing'
    | '/immigration'
    | '/wills-probate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommercialPropertyRoute: typeof CommercialPropertyRoute
  ConveyancingRoute: typeof ConveyancingRoute
  ImmigrationRoute: typeof ImmigrationRoute
  WillsProbateRoute: typeof WillsProbateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wills-probate': {
      id: '/wills-probate'
      path: '/wills-probate'
      fullPath: '/wills-probate'
      preLoaderRoute: typeof WillsProbateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immigration': {
      id: '/immigration'
      path: '/immigration'
      fullPath: '/immigration'
      preLoaderRoute: typeof ImmigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conveyancing': {
      id: '/conveyancing'
      path: '/conveyancing'
      fullPath: '/conveyancing'
      preLoaderRoute: typeof ConveyancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial-property': {
      id: '/commercial-property'
      path: '/commercial-property'
      fullPath: '/commercial-property'
      preLoaderRoute: typeof CommercialPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommercialPropertyRoute: CommercialPropertyRoute,
  ConveyancingRoute: ConveyancingRoute,
  ImmigrationRoute: ImmigrationRoute,
  WillsProbateRoute: WillsProbateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
